# Docker Hub to Cloud Run Deployment Configuration
# Update these values according to your Docker Hub image and requirements

# Docker Hub Image Configuration
docker_image: "your-dockerhub-username/your-image:latest"
# Examples:
# - "nginx:latest"
# - "myapp:1.0.0"
# - "username/myapp:latest"

# Cloud Run Service Configuration
service_name: "dockerhub-app"
region: "us-central1"
port: "8080"

# Resource Configuration
memory: "512Mi"
cpu: "1"

# Environment Variables (optional)
environment_variables:
  - "ENVIRONMENT=production"
  - "NODE_ENV=production"
  # Add more environment variables as needed

# Scaling Configuration (optional)
min_instances: "0"
max_instances: "10"

# Network Configuration (optional)
# vpc_connector: "projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME"

# Secrets Configuration (optional)
# secrets:
#   - "DATABASE_URL=projects/PROJECT_ID/secrets/DATABASE_URL/versions/latest"
#   - "API_KEY=projects/PROJECT_ID/secrets/API_KEY/versions/latest" 